# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
      - 'manage-functions/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'manage-functions/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.2'

    - name: Build
      run: |
        cd manage-functions/
        go build -o manage-functions . 
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.2'
    - name: Login to Docker Hub
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: manage-functions
        file: manage-functions/Dockerfile
        push: true
        tags: |
          zshsz/manage-functions:${{ github.sha }}
          zshsz/manage-functions:latest
        build-args: |
          VERSION=${{ github.sha }}
      env:
        DOCKER_BUILDKIT: 1
    
